# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

orbs:
  # Declare a dependency on the welcome-orb
  node: circleci/node@4.2.0
  new-relic-events: dhcs/new-relic-events@0.0.4

jobs: 
  test_and_push_to_newrelic: 
    docker: 
      - image: cimg/node:15.11.0
    steps:
      - checkout
      - node/install-packages
      - run: npm run run_tests
      - run:
          command: |
            PAYLOAD=`cat payload.json`
      - new-relic-events/custom-event:
          events: $PAYLOAD
          nr-account-id: $NewRelicAccount
          nr-insert-key: $NewRelicKey
        
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  daniel:
    # Run the welcome/run job in its own container
    jobs:
      - test_and_push_to_newrelic
